apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: davtrokustomize

resources:
  - ../base

images:
  - name: ghcr.io/exea-centrum/website-simple-argocd-k8s-github-kustomize
    newTag: f326b0dff7c32d2e0ed2c651351adca105a2e8fc

replicas:
  - name: website-game-theory
    count: 2
