name: Build and Push to GHCR

on:
  push:
    branches:
      - main

permissions:
  contents: read # wymagane przez checkout
  packages: write # wymagane do push do GHCR

env:
  IMAGE_NAME: website-argocd-k8s-github-kustomize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 🔹 Logowanie do GHCR – użyje GHCR_PAT jeśli dostępny, w przeciwnym razie GITHUB_TOKEN
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT || secrets.GITHUB_TOKEN }}

      # 🔹 Budowanie i publikacja obrazu
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 🔹 (Opcjonalnie) wypisz link do obrazu w GHCR
      - name: Show image URL
        run: echo "✅ Image pushed to ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
